
services:
  neo4j:
    image: neo4j:latest
    container_name: synapse-neo4j
    ports:
      - "7687:7687"  # Bolt protocol
      - "7474:7474"  # HTTP interface
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "MATCH () RETURN count(*) as count"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  synapse-server:
    build: .
    container_name: synapse-mcp-server
    ports:
      - "8080:8080"  # MCP server API
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - RUST_LOG=info
      - SYNAPSE_VERBOSE=false
    volumes:
      - ./rules_examples:/app/rules_examples:ro  # Mount example rules
      - synapse_data:/data
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped
    command: ["serve", "--host", "0.0.0.0", "--port", "8080", "--enable-enforcer"]
    healthcheck:
      test: ["CMD", "synapse", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  synapse_data:
    driver: local